language: node_js

node_js:
 - "8"
 - "10"

addons:
  code_climate:
    repo_token: 6dc47f6e0d95f643d41d7e15941b0c26c87214b4362c6aa01cf1e465eaeae0d3

branches:
  only:
    - master

sudo: false

services:
- mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

install:
 - npm install

before_script:
 - npm run lint

after_script: 
  - npm run test:coveralls
